name: arcade
description: "Create stunning user interfaces with beautifully crafted Flutter widgets."
publish_to: "none"
homepage: "https://arcade.medz.dev"
repository: https://github.com/medz/flutter-arcade-ui

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  go_router: ^17.0.0
  flutter_markdown_plus: ^1.0.5
  flutter_highlight: ^0.7.0
  google_fonts: ^6.3.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/widgets/backgrounds/
    - lib/widgets/navigations/
    - lib/widgets/borders/
    - lib/widgets/cards/
    - docs/
    - docs/widgets/backgrounds/
    - docs/widgets/navigations/
    - docs/widgets/borders/
    - docs/widgets/cards/
